const tripStore = require("../../utils/tripStore");
const TYPES = [{ key: "hotel", label: "酒店" }, { key: "restaurant", label: "餐厅" }, { key: "transport", label: "交通" }, { key: "attraction", label: "景点" }, { key: "custom", label: "其他" }];
Page({
  data: { id: "", trip: null, days: [], conflicts: [], itemForm: { title: "", type: "custom", date: "", startTime: "", endTime: "", note: "" }, showForm: false, editingItemId: "", types: TYPES },
  onLoad(options) { this.setData({ id: options.id || "" }); },
  onShow() { this.load(); },
  load() { const trip = tripStore.getTripById(this.data.id); if (!trip) return; const conflicts = tripStore.findConflicts(trip.itineraryItems); const conflictIds = new Set([].concat(...conflicts)); const days = tripStore.dateRange(trip.startDate, trip.endDate).map((date) => ({ date, label: `${Number(date.slice(5, 7))}月${Number(date.slice(8))}日`, items: trip.itineraryItems.filter((item) => item.date === date).sort((a, b) => a.startTime.localeCompare(b.startTime)).map((item) => ({ ...item, conflict: conflictIds.has(item.id), typeLabel: (TYPES.find((type) => type.key === item.type) || TYPES[4]).label })) })); this.setData({ trip: { ...trip, cityText: trip.cities.join("、") || "目的地待定" }, days, conflicts }); },
  edit() { wx.navigateTo({ url: `/pages/trip/edit?id=${this.data.id}` }); }, budget() { wx.navigateTo({ url: `/pages/trip/budget?id=${this.data.id}` }); },
  toggleForm() { this.setData({ showForm: !this.data.showForm, editingItemId: "", itemForm: { title: "", type: "custom", date: this.data.trip.startDate, startTime: "", endTime: "", note: "" } }); }, input(event) { this.setData({ [`itemForm.${event.currentTarget.dataset.field}`]: event.detail.value }); }, choose(event) { this.setData({ [`itemForm.${event.currentTarget.dataset.field}`]: event.detail.value }); }, type(event) { this.setData({ "itemForm.type": event.currentTarget.dataset.value }); },
  editItem(event) { const item = this.data.trip.itineraryItems.find((entry) => entry.id === event.currentTarget.dataset.id); if (!item) return; this.setData({ showForm: true, editingItemId: item.id, itemForm: { title: item.title, type: item.type, date: item.date, startTime: item.startTime, endTime: item.endTime, note: item.note } }); },
  add() { if (!this.data.itemForm.title.trim()) return wx.showToast({ title: "请填写日程名称", icon: "none" }); try { if (this.data.editingItemId) tripStore.updateItineraryItem(this.data.id, this.data.editingItemId, this.data.itemForm); else tripStore.addItineraryItem(this.data.id, this.data.itemForm); this.setData({ showForm: false, editingItemId: "" }); this.load(); } catch (error) { wx.showToast({ title: error.message, icon: "none" }); } },
  remove(event) { const itemId = event.currentTarget.dataset.id; wx.showModal({ title: "删除日程", content: "确认删除这项安排吗？", success: (result) => { if (result.confirm) { tripStore.removeItineraryItem(this.data.id, itemId); this.load(); } } }); },
  duplicate() { const copy = tripStore.duplicateTrip(this.data.id); if (copy) wx.navigateTo({ url: `/pages/trip/detail?id=${copy.id}` }); }
});
