const { createId } = require("./id");
const STORAGE_KEY = "experience_form_templates";
const SAFE_FIELDS = ["recordType", "roomType", "memberLevel", "cuisine", "selectedTags"];
const BUILT_INS = [{ id: "builtin_business", name: "商务入住", type: "hotel", fields: { type: "hotel" } }, { id: "builtin_resort", name: "度假酒店", type: "hotel", fields: { type: "hotel" } }, { id: "builtin_lounge", name: "行政酒廊体验", type: "hotel", fields: { type: "hotel" } }, { id: "builtin_breakfast", name: "早餐专项", type: "hotel", fields: { type: "hotel" } }, { id: "builtin_michelin", name: "米其林正餐", type: "restaurant", fields: { type: "restaurant" } }, { id: "builtin_quick", name: "餐厅快速记录", type: "restaurant", fields: { type: "restaurant" } }];
function sanitizeFields(source = {}) { return SAFE_FIELDS.reduce((result, key) => { if (source[key] !== undefined) result[key] = JSON.parse(JSON.stringify(source[key])); return result; }, {}); }
function getTemplates() { const raw = wx.getStorageSync(STORAGE_KEY); return BUILT_INS.concat(Array.isArray(raw) ? raw : []); }
function saveTemplate(name, source) { const cleanName = String(name || "").trim(); if (!cleanName) throw new Error("模板名称不能为空"); const raw = wx.getStorageSync(STORAGE_KEY); const item = { id: createId("template"), name: cleanName, type: (source.recordType || source.type) === "restaurant" ? "restaurant" : "hotel", fields: sanitizeFields(source), createdAt: new Date().toISOString() }; wx.setStorageSync(STORAGE_KEY, [item].concat(Array.isArray(raw) ? raw : [])); return item; }
function deleteTemplate(id) { if (String(id).indexOf("builtin_") === 0) throw new Error("内置模板不能删除"); const raw = wx.getStorageSync(STORAGE_KEY); wx.setStorageSync(STORAGE_KEY, (Array.isArray(raw) ? raw : []).filter((item) => item.id !== String(id))); }
function applyTemplate(form, template) { return { ...form, ...sanitizeFields(template.fields || {}) }; }
function buildRecentSuggestions(records, form = {}) { const keyword = String(form.displayName || form.hotelName || form.restaurantName || "").trim().toLowerCase(); const matched = (records || []).filter((record) => !keyword || String(record.displayName || "").toLowerCase().indexOf(keyword) >= 0).slice().sort((a, b) => String(b.updatedAt || b.createdAt).localeCompare(String(a.updatedAt || a.createdAt))); const latest = matched[0] || {}; const tags = []; matched.forEach((record) => (record.selectedTags || []).forEach((tag) => { if (tags.indexOf(tag) < 0) tags.push(tag); })); return { city: latest.city || "", roomType: latest.roomType || "", memberLevel: latest.memberLevel || "", cuisine: latest.cuisine || "", tags: tags.slice(0, 8) }; }
module.exports = { BUILT_INS, STORAGE_KEY, applyTemplate, buildRecentSuggestions, deleteTemplate, getTemplates, sanitizeFields, saveTemplate };
