const { createId } = require("./id");

const STORAGE_KEY = "experience_trips";
const CATEGORIES = ["住宿", "餐饮", "交通", "门票", "购物", "其他"];
const ITEM_TYPES = ["hotel", "restaurant", "transport", "attraction", "custom"];

function clone(value) { return JSON.parse(JSON.stringify(value)); }
function cents(value) { const text = String(value == null ? "" : value).trim(); if (!/^\d+(\.\d{0,2})?$/.test(text)) return 0; const parts = text.split("."); return Number(parts[0]) * 100 + Number((parts[1] || "").padEnd(2, "0")); }
function money(value) { return `¥${Math.floor(Number(value || 0) / 100)}.${String(Number(value || 0) % 100).padStart(2, "0")}`; }
function dateRange(start, end) { const days = []; if (!start || !end || start > end) return days; const cursor = new Date(`${start}T00:00:00Z`); const last = new Date(`${end}T00:00:00Z`); while (cursor <= last && days.length < 370) { days.push(cursor.toISOString().slice(0, 10)); cursor.setUTCDate(cursor.getUTCDate() + 1); } return days; }

function normalizeItem(input = {}) {
  return { id: String(input.id || createId("plan")), type: ITEM_TYPES.indexOf(input.type) >= 0 ? input.type : "custom", title: String(input.title || "").trim(), date: String(input.date || ""), startTime: String(input.startTime || ""), endTime: String(input.endTime || ""), sortOrder: Number.isFinite(Number(input.sortOrder)) ? Number(input.sortOrder) : 0, city: String(input.city || "").trim(), placeId: String(input.placeId || ""), wishlistId: String(input.wishlistId || ""), recordId: String(input.recordId || ""), bookingId: String(input.bookingId || ""), bookingStatus: String(input.bookingStatus || "planned"), estimatedCents: Number(input.estimatedCents || 0), note: String(input.note || "").trim() };
}

function normalizeTrip(input = {}) {
  const categoryBudgets = CATEGORIES.reduce((result, category) => { result[category] = Number((input.categoryBudgets || {})[category] || 0); return result; }, {});
  return { id: String(input.id || createId("trip")), title: String(input.title || "").trim(), cities: Array.isArray(input.cities) ? input.cities.map(String).filter(Boolean) : String(input.cities || "").split(/[、,，]/).map((item) => item.trim()).filter(Boolean), startDate: String(input.startDate || ""), endDate: String(input.endDate || ""), participantIds: Array.isArray(input.participantIds) ? input.participantIds.map(String) : [], baseCurrency: String(input.baseCurrency || "CNY").toUpperCase(), budgetTotalCents: Number(input.budgetTotalCents || 0), categoryBudgets, itineraryItems: (input.itineraryItems || []).map(normalizeItem), linkedLedgerIds: Array.isArray(input.linkedLedgerIds) ? input.linkedLedgerIds.map(String) : [], personalExpenses: (input.personalExpenses || []).map((item) => ({ id: String(item.id || createId("personal")), title: String(item.title || "").trim(), category: CATEGORIES.indexOf(item.category) >= 0 ? item.category : "其他", date: String(item.date || ""), originalAmountCents: Number(item.originalAmountCents || item.amountCents || 0), currency: String(item.currency || input.baseCurrency || "CNY").toUpperCase(), rate: Number(item.rate || 1), amountCents: Number(item.amountCents || 0), bookingId: String(item.bookingId || ""), note: String(item.note || "").trim() })), note: String(input.note || "").trim(), status: ["upcoming", "active", "ended", "archived"].indexOf(input.status) >= 0 ? input.status : "upcoming", createdAt: input.createdAt || new Date().toISOString(), updatedAt: input.updatedAt || "" };
}

function validateTrip(trip) { if (!trip.title) throw new Error("行程名称不能为空"); if (!trip.startDate || !trip.endDate) throw new Error("请选择行程日期"); if (trip.startDate > trip.endDate) throw new Error("结束日期不能早于开始日期"); trip.itineraryItems.forEach((item) => { if (item.date && (item.date < trip.startDate || item.date > trip.endDate)) throw new Error("日程日期超出行程范围"); }); return trip; }
function getTrips() { const raw = wx.getStorageSync(STORAGE_KEY); return (Array.isArray(raw) ? raw : []).map(normalizeTrip).sort((a, b) => String(b.updatedAt || b.createdAt).localeCompare(String(a.updatedAt || a.createdAt))); }
function setTrips(items) { const normalized = items.map(normalizeTrip); wx.setStorageSync(STORAGE_KEY, normalized); return normalized; }
function getTripById(id) { return getTrips().find((item) => item.id === String(id)) || null; }
function addTrip(input) { const now = new Date().toISOString(); const trip = validateTrip(normalizeTrip({ ...input, id: createId("trip"), createdAt: now, updatedAt: now })); setTrips([trip].concat(getTrips())); return trip; }
function updateTrip(id, patch) { let updated = null; const items = getTrips().map((trip) => { if (trip.id !== String(id)) return trip; updated = validateTrip(normalizeTrip({ ...trip, ...patch, id: trip.id, createdAt: trip.createdAt, updatedAt: new Date().toISOString() })); return updated; }); if (!updated) return null; setTrips(items); return updated; }
function deleteTrip(id) { const trip = getTripById(id); if (!trip) return false; if (trip.itineraryItems.length || trip.personalExpenses.length || trip.linkedLedgerIds.length) throw new Error("请先清空日程、支出和关联账本"); setTrips(getTrips().filter((item) => item.id !== String(id))); return true; }
function duplicateTrip(id) { const source = getTripById(id); if (!source) return null; return addTrip({ ...source, title: `${source.title} 副本`, status: "upcoming", itineraryItems: source.itineraryItems.map((item) => ({ ...item, id: createId("plan"), recordId: "", bookingId: "", bookingStatus: "planned" })), linkedLedgerIds: [], personalExpenses: [] }); }
function addItineraryItem(id, input) { const trip = getTripById(id); if (!trip) return null; const sameDay = trip.itineraryItems.filter((item) => item.date === String(input.date || "")); const sortOrder = sameDay.reduce((max, item) => Math.max(max, Number(item.sortOrder || 0)), -1) + 1; return updateTrip(id, { itineraryItems: trip.itineraryItems.concat(normalizeItem({ ...input, sortOrder })) }); }
function updateItineraryItem(id, itemId, patch) { const trip = getTripById(id); if (!trip) return null; return updateTrip(id, { itineraryItems: trip.itineraryItems.map((item) => item.id === String(itemId) ? normalizeItem({ ...item, ...patch, id: item.id }) : item) }); }
function duplicateItineraryItem(id, itemId) { const trip = getTripById(id); if (!trip) return null; const source = trip.itineraryItems.find((item) => item.id === String(itemId)); if (!source) return null; return addItineraryItem(id, { ...source, id: createId("plan"), title: `${source.title} 副本`, recordId: "", bookingId: "", bookingStatus: "planned" }); }
function moveItineraryItem(id, itemId, direction) { const trip = getTripById(id); if (!trip) return null; const target = trip.itineraryItems.find((item) => item.id === String(itemId)); if (!target) return null; const dayItems = trip.itineraryItems.filter((item) => item.date === target.date).sort((a, b) => Number(a.sortOrder || 0) - Number(b.sortOrder || 0) || a.startTime.localeCompare(b.startTime)); const index = dayItems.findIndex((item) => item.id === target.id); const nextIndex = direction === "up" ? index - 1 : index + 1; if (nextIndex < 0 || nextIndex >= dayItems.length) return trip; const other = dayItems[nextIndex]; return updateTrip(id, { itineraryItems: trip.itineraryItems.map((item) => item.id === target.id ? { ...item, sortOrder: Number(other.sortOrder || nextIndex) } : item.id === other.id ? { ...item, sortOrder: Number(target.sortOrder || index) } : item) }); }
function removeItineraryItem(id, itemId) { const trip = getTripById(id); return trip ? updateTrip(id, { itineraryItems: trip.itineraryItems.filter((item) => item.id !== String(itemId)) }) : null; }
function findConflicts(items) { const sorted = items.filter((item) => item.date && item.startTime).slice().sort((a, b) => `${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`)); const conflicts = []; sorted.forEach((item, index) => { const next = sorted[index + 1]; if (next && item.date === next.date && (!item.endTime || item.endTime > next.startTime)) conflicts.push([item.id, next.id]); }); return conflicts; }
function addPersonalExpense(id, input) { const trip = getTripById(id); if (!trip) return null; const originalAmountCents = input.originalAmountCents == null ? cents(input.amountText) : Number(input.originalAmountCents); const rate = input.rate == null || input.rate === "" ? 1 : Number(input.rate); if (!(originalAmountCents > 0) || !(rate > 0)) throw new Error("请输入有效金额和汇率"); const amountCents = Math.round(originalAmountCents * rate); return updateTrip(id, { personalExpenses: trip.personalExpenses.concat({ ...input, id: createId("personal"), originalAmountCents, rate, amountCents }) }); }
function updatePersonalExpense(id, expenseId, patch) { const trip = getTripById(id); if (!trip) return null; const current = trip.personalExpenses.find((item) => item.id === String(expenseId)); if (!current) return null; const originalAmountCents = patch.originalAmountCents == null ? cents(patch.amountText == null ? current.originalAmountCents / 100 : patch.amountText) : Number(patch.originalAmountCents); const rate = patch.rate == null || patch.rate === "" ? Number(current.rate || 1) : Number(patch.rate); if (!(originalAmountCents > 0) || !(rate > 0)) throw new Error("请输入有效金额和汇率"); const updated = { ...current, ...patch, id: current.id, originalAmountCents, rate, amountCents: Math.round(originalAmountCents * rate) }; return updateTrip(id, { personalExpenses: trip.personalExpenses.map((item) => item.id === current.id ? updated : item) }); }
function removePersonalExpense(id, expenseId) { const trip = getTripById(id); return trip ? updateTrip(id, { personalExpenses: trip.personalExpenses.filter((item) => item.id !== String(expenseId)) }) : null; }
function calculateBudget(trip, ledgers = []) { const normalized = normalizeTrip(trip); const linked = new Set(normalized.linkedLedgerIds); const ledgerExpenses = (ledgers || []).filter((ledger) => linked.has(ledger.id)).reduce((items, ledger) => items.concat(ledger.expenses || []), []); const personalCents = normalized.personalExpenses.reduce((sum, item) => sum + Number(item.amountCents || 0), 0); const ledgerCents = ledgerExpenses.reduce((sum, item) => sum + Number(item.amountCents || 0), 0); const rows = normalized.personalExpenses.concat(ledgerExpenses.map((expense) => ({ amountCents: Number(expense.amountCents || 0), category: expense.category || "其他", source: "ledger" }))); const byCategory = CATEGORIES.reduce((map, category) => { map[category] = 0; return map; }, {}); rows.forEach((item) => { const category = CATEGORIES.indexOf(item.category) >= 0 ? item.category : "其他"; byCategory[category] += Number(item.amountCents || 0); }); const spentCents = personalCents + ledgerCents; return { spentCents, spentText: money(spentCents), personalCents, personalText: money(personalCents), personalExpenseCount: normalized.personalExpenses.length, ledgerCents, ledgerText: money(ledgerCents), ledgerExpenseCount: ledgerExpenses.length, remainingCents: normalized.budgetTotalCents - spentCents, remainingText: money(Math.abs(normalized.budgetTotalCents - spentCents)), percent: normalized.budgetTotalCents ? Math.round(spentCents / normalized.budgetTotalCents * 100) : 0, overBudget: normalized.budgetTotalCents > 0 && spentCents > normalized.budgetTotalCents, byCategory: CATEGORIES.map((category) => ({ category, spentCents: byCategory[category], spentText: money(byCategory[category]), budgetCents: normalized.categoryBudgets[category], budgetText: money(normalized.categoryBudgets[category]), over: normalized.categoryBudgets[category] > 0 && byCategory[category] > normalized.categoryBudgets[category] })) }; }

module.exports = { CATEGORIES, ITEM_TYPES, STORAGE_KEY, addItineraryItem, addPersonalExpense, addTrip, calculateBudget, cents, dateRange, deleteTrip, duplicateItineraryItem, duplicateTrip, findConflicts, getTripById, getTrips, money, moveItineraryItem, normalizeTrip, removeItineraryItem, removePersonalExpense, setTrips, updateItineraryItem, updatePersonalExpense, updateTrip, validateTrip };
